[package]
name = "mlpl-extension-http-client"
version = "0.0.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
mlpl-extension-sdk = { path = "../../crates/mlpl-extension-sdk" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
ureq = { version = "2.12.1", default-features = false, features = ["tls"] }
url = "2"

[dev-dependencies]
mlpl-extension-loader = { path = "../../crates/mlpl-extension-loader" }

[lints]
workspace = true
